const List<String> categoryData = [
  "Actor",
  "Dancer",
  "Writer",
  "Musician",
  "Painter",
  "Chirographer",
  "Singer",
  "Designer",
  "Chef",
];

const List<String> myApplicationData = [
  "Applied",
  "Shortlisted",
  "Accepted",
  "Declined",
  "Bookmark",
];

const List<List<String>> applicationAppliedData = [
  [
    "Esther Howard",
    "Egestas eget gravida dui neque, eu nunc.",
    "asset/images/uiImages/1.png",
  ],
  [
    "Savannah Nguyen",
    "Morbi semper risus aliquet nunc orci scelerisque sed elit, sodales.",
    "asset/images/uiImages/3.png",
  ],
];

const List<String> inboxData = [
  "Messages",
  "Notifications",
];

const List<List<String>> inboxMessageData = [
  [
    "Cameron Williamson",
    "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.",
    "asset/images/uiImages/8.png",
  ],
  [
    "Dianne Russell",
    "Auctor arcu, vulputate tempor elementum malesuada.",
    "asset/images/uiImages/10.png",
  ],
  [
    "Jerome Bell",
    "Diam fementum molestie odio faucibus hendrerit volutpat sit.",
    "asset/images/uiImages/2.png",
  ],
];

const List<String> imageData = [
  "https://images.unsplash.com/photo-1517841905240-472988babdf9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
  "https://images.unsplash.com/photo-1531734510209-2da4a139a53a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
  "https://images.unsplash.com/photo-1523824921871-d6f1a15151f1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
  "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
  "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80",
  "https://images.unsplash.com/photo-1523419409543-a5e549c1faa8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=697&q=80",
];

// const List<List<String>> actorData = [
//   [
//     "Diam ullamcorper",
//     "Sed neque, ac",
//     "Tempor ante ullamcorper tortor cras morbi urna vestibulum, se......",
//     "asset/images/uiImages/1.png",
//   ],
//   [
//     "Leo ultrices",
//     "Tincidunt pellentesque",
//     "Tempor ante ullamcorper tortor cras morbi urna vestibulum, se......",
//     "asset/images/uiImages/2.png",
//   ],
//   [
//     "Purus vestibulum",
//     "Vitae a massa",
//     "Tempor ante ullamcorper tortor cras morbi urna vestibulum, se......",
//     "asset/images/uiImages/3.png",
//   ],
//   [
//     "Sed scelerisque",
//     "Lacus, dui eu",
//     "Tempor ante ullamcorper tortor cras morbi urna vestibulum, se......",
//     "asset/images/uiImages/4.png",
//   ],
//   [
//     "Gravida luctus",
//     "Nam varius eget",
//     "Tempor ante ullamcorper tortor cras morbi urna vestibulum, se......",
//     "asset/images/uiImages/5.png",
//   ],
//   [
//     "Dictum dui",
//     "Risus posuere ipsum",
//     "Tempor ante ullamcorper tortor cras morbi urna vestibulum, se......",
//     "asset/images/uiImages/6.png",
//   ],
//   [
//     "Sapien, maecenas",
//     "Amet dolor sit",
//     "Tempor ante ullamcorper tortor cras morbi urna vestibulum, se......",
//     "asset/images/uiImages/7.png",
//   ],
//   [
//     "Vivamus non",
//     "Aliquam non id",
//     "Tempor ante ullamcorper tortor cras morbi urna vestibulum, se......",
//     "asset/images/uiImages/8.png",
//   ],
//   [
//     "Pulvinar eu",
//     "Quis tempus sit",
//     "Tempor ante ullamcorper tortor cras morbi urna vestibulum, se......",
//     "asset/images/uiImages/9.png",
//   ],
//   [
//     "Faucibus tortor",
//     "Tellus in egestas",
//     "Tempor ante ullamcorper tortor cras morbi urna vestibulum, se......",
//     "asset/images/uiImages/10.png",
//   ],
// ];

const List<String> profileData = [
  "Basic Info",
  "Appearance",
  "Website/Social Media",
  "Union Membership",
  "Skills",
  "Credits",
  "Subscription",
  "Create Another Profile",
];

const List<String> profileMediaData = [
  "Photos",
  "Videos",
  "Audios",
  "Documents",
  "Draft",
];

const List<String> mediaPicData = [
  "asset/images/uiImages/m1.png",
  "asset/images/uiImages/m2.png",
  "asset/images/uiImages/face.png",
  "asset/images/uiImages/m3.png",
  "asset/images/uiImages/m4.png",
  "asset/images/uiImages/m5.png",
  "asset/images/uiImages/m6.png",
  "asset/images/uiImages/m7.png",
];

const List<String> mediaVideoData = [
  "asset/images/uiImages/mv1.png",
  "asset/images/uiImages/mv2.png",
  "asset/images/uiImages/mv3.png",
];

const List<String> membershipData = [
  "Nonunion",
  "SAG-AFTRA",
  "Equity (U.S.)",
  "Equity (U.K.)",
  "Equity (Canada)",
  "Equity (Ireland)",
  "Equity (Australia)",
  "Equity (New Zealand)",
];

const List<List<String>> subscriptionPlans = [
  [
    "Gold",
    "Adipiscing lobortis fermentum, in parturient interdum sed sit augue pellentesque. Est metus, purus, at habitasse blandit cursus.",
  ],
  [
    "Platinum",
    "Adipiscing lobortis fermentum, in parturient interdum sed sit augue pellentesque. Est metus, purus, at habitasse blandit cursus.",
  ],
];

const List<String> descriptionData = [
  "\"Commodo pretium consectetur pharetra, id dictum nisi rhoncus. Quis a posuere scelerisque et, mi gravida non est mollis. Lorem molestie pulvinar consectetur massa. Fringilla risus, facillsi pulvinar luctus adipiscing. Massa iaculis sed egestas risus in sit. Urna, gravida amet a pellenstesque id nullam. Potenti ac, purus eget quam set imperdiet quam sagittis, semper. Phasellus justo, mattis leo, mattis conseq.\" Massa iaculis sed egestas risus in sit. Urna, gravida amet a pellenstesque id nullam. Potenti ac, purus eget quam set imperdiet quam sagittis, semper. Phasellus justo, mattis leo, mattis conseq.",
  "\"Molestie pulvinar consectetur massa. Fringilla risus, facilisi pulvinar luctus adipiscing. Massa iaculis sed egestas risus in sit. Urna, gravida amet a pellentesque id nullam. Potenti ac, purus eget quam sed imperdiet\"",
  "Quam ultricies risus aliquam at in vel blandit. Arcu blandit nibh egestas egestas. Libero, amet non posuere hendreit et blandit interdum urna quis. Faucibus mauris proin placerat proin massa. Molestie pharetra set aliquent ultricies elit eu, et quis amet.",
];

const List<String> pronounData = [
  "He/Him",
  "She/Her",
  "Mr.",
  "Mrs.",
  "Miss",
  "Dr.",
];

const List<String> genderData = [
  "Male",
  "Female",
  "Others",
];

const List<String> locationData = [
  "China",
  "India",
  "United States",
  "Indonesia",
  "Brazil",
  "Pakistan",
  "Nigeria",
  "Bangladesh",
  "Russia",
  "Japan",
  "Mexico",
  "Philippines",
  "Vietnam",
  "Ethiopia",
  "Egypt",
  "Germany",
  "Iran",
  "Turkey",
  "Democratic Republic of the Congo",
  "Thailand",
  "France",
  "United Kingdom",
  "Italy",
  "Burma",
  "South Africa",
  "South Korea",
  "Colombia",
  "Spain",
  "Ukraine",
  "Tanzania",
  "Kenya",
  "Argentina",
  "Algeria",
  "Poland",
  "Sudan",
  "Uganda",
  "Canada",
  "Iraq",
  "Morocco",
  "Peru",
  "Uzbekistan",
  "Saudi Arabia",
  "Malaysia",
  "Venezuela",
  "Nepal",
  "Afghanistan",
  "Yemen",
  "North Korea",
  "Ghana",
  "Mozambique",
  "Taiwan",
  "Australia",
  "Ivory Coast",
  "Syria",
  "Madagascar",
  "Angola",
  "Cameroon",
  "Sri Lanka",
  "Romania",
  "Burkina Faso",
  "Niger",
  "Kazakhstan",
  "Netherlands",
  "Chile",
  "Malawi",
  "Ecuador",
  "Guatemala",
  "Mali",
  "Cambodia",
  "Senegal",
  "Zambia",
  "Zimbabwe",
  "Chad",
  "South Sudan",
  "Belgium",
  "Cuba",
  "Tunisia",
  "Guinea",
  "Greece",
  "Portugal",
  "Rwanda",
  "Czech Republic",
  "Somalia",
  "Haiti",
  "Benin",
  "Burundi",
  "Bolivia",
  "Hungary",
  "Sweden",
  "Belarus",
  "Dominican Republic",
  "Azerbaijan",
  "Honduras",
  "Austria",
  "United Arab Emirates",
  "Israel",
  "Switzerland",
  "Tajikistan",
  "Bulgaria",
  "Hong Kong (China)",
  "Serbia",
  "Papua New Guinea",
  "Paraguay",
  "Laos",
  "Jordan",
  "El Salvador",
  "Eritrea",
  "Libya",
  "Togo",
  "Sierra Leone",
  "Nicaragua",
  "Kyrgyzstan",
  "Denmark",
  "Finland",
  "Slovakia",
  "Singapore",
  "Turkmenistan",
  "Norway",
  "Lebanon",
  "Costa Rica",
  "Central African Republic",
  "Ireland",
  "Georgia",
  "New Zealand",
  "Republic of the Congo",
  "Palestine",
  "Liberia",
  "Croatia",
  "Oman",
  "Bosnia and Herzegovina",
  "Puerto Rico",
  "Kuwait",
  "Moldov",
  "Mauritania",
  "Panama",
  "Uruguay",
  "Armenia",
  "Lithuania",
  "Albania",
  "Mongolia",
  "Jamaica",
  "Namibia",
  "Lesotho",
  "Qatar",
  "Macedonia",
  "Slovenia",
  "Botswana",
  "Latvia",
  "Gambia",
  "Kosovo",
  "Guinea-Bissau",
  "Gabon",
  "Equatorial Guinea",
  "Trinidad and Tobago",
  "Estonia",
  "Mauritius",
  "Swaziland",
  "Bahrain",
  "Timor-Leste",
  "Djibouti",
  "Cyprus",
  "Fiji",
  "Reunion (France)",
  "Guyana",
  "Comoros",
  "Bhutan",
  "Montenegro",
  "Macau (China)",
  "Solomon Islands",
  "Western Sahara",
  "Luxembourg",
  "Suriname",
  "Cape Verde",
  "Malta",
  "Guadeloupe (France)",
  "Martinique (France)",
  "Brunei",
  "Bahamas",
  "Iceland",
  "Maldives",
  "Belize",
  "Barbados",
  "French Polynesia (France)",
  "Vanuatu",
  "New Caledonia (France)",
  "French Guiana (France)",
  "Mayotte (France)",
  "Samoa",
  "Sao Tom and Principe",
  "Saint Lucia",
  "Guam (USA)",
  "Curacao (Netherlands)",
  "Saint Vincent and the Grenadines",
  "Kiribati",
  "United States Virgin Islands (USA)",
  "Grenada",
  "Tonga",
  "Aruba (Netherlands)",
  "Federated States of Micronesia",
  "Jersey (UK)",
  "Seychelles",
  "Antigua and Barbuda",
  "Isle of Man (UK)",
  "Andorra",
  "Dominica",
  "Bermuda (UK)",
  "Guernsey (UK)",
  "Greenland (Denmark)",
  "Marshall Islands",
  "American Samoa (USA)",
  "Cayman Islands (UK)",
  "Saint Kitts and Nevis",
  "Northern Mariana Islands (USA)",
  "Faroe Islands (Denmark)",
  "Sint Maarten (Netherlands)",
  "Saint Martin (France)",
  "Liechtenstein",
  "Monaco",
  "San Marino",
  "Turks and Caicos Islands (UK)",
  "Gibraltar (UK)",
  "British Virgin Islands (UK)",
  "Aland Islands (Finland)",
  "Caribbean Netherlands (Netherlands)",
  "Palau",
  "Cook Islands (NZ)",
  "Anguilla (UK)",
  "Wallis and Futuna (France)",
  "Tuvalu",
  "Nauru",
  "Saint Barthelemy (France)",
  "Saint Pierre and Miquelon (France)",
  "Montserrat (UK)",
  "Saint Helena, Ascension and Tristan da Cunha (UK)",
  "Svalbard and Jan Mayen (Norway)",
  "Falkland Islands (UK)",
  "Norfolk Island (Australia)",
  "Christmas Island (Australia)",
  "Niue (NZ)",
  "Tokelau (NZ)",
  "Vatican City",
  "Cocos (Keeling) Islands (Australia)",
  "Pitcairn Islands (UK)",
];

const List<String> ethnicitiesData = [
  "Asian",
  "Black",
  "Hispanic/Latin",
  "Indian",
  "Middle Eastern",
  "Native American",
  "Pacific Islander",
  "White",
  "Other ethnicity",
];

const List<String> heightData = [
  "2'11\"",
  "3'0\"",
  "3'1\"",
  "3'2\"",
  "3'3\"",
  "3'4\"",
  "3'5\"",
  "3'6\"",
  "3'7\"",
  "3'8\"",
  "3'9\"",
  "3'10\"",
  "3'11\"",
  "4'0\"",
  "4'1\"",
  "4'2\"",
  "4'3\"",
  "4'4\"",
  "4'5\"",
  "4'6\"",
  "4'7\"",
  "4'8\"",
  "4'9\"",
  "4'10\"",
  "4'11\"",
  "5'0\"",
  "5'1\"",
  "5'2\"",
  "5'3\"",
  "5'4\"",
  "5'5\"",
  "5'6\"",
  "5'7\"",
  "5'8\"",
  "5'9\"",
  "5'10\"",
  "5'11\"",
  "6'0\"",
  "6'1\"",
  "6'2\"",
  "6'3\"",
  "6'4\"",
  "6'5\"",
  "6'6\"",
  "6'7\"",
  "6'8\"",
  "6'9\"",
  "6'10\"",
  "6'11\"",
  "7'0\"",
  "7'1\"",
  "7'2\"",
  "7'3\"",
  "7'4\"",
  "7'5\"",
  "7'6\"",
  "7'7\"",
  "7'8\"",
  "7'9\"",
  "7'10\"",
  "7'11\"",
  "8'0\"",
];

const List<String> bodyTypeData = [
  "Thin",
  "Overweight",
  "Average",
  "Fit",
  "Jacked",
  "A little extra",
  "Curvy",
  "Full figured"
];

const List<String> hairColorData = [
  "Black",
  "Natural Black",
  "Dark Brown",
  "Medium Brown",
  "Natural Brown",
  "Light Brown",
  "Chestnut Brown",
  "Light Chestnut Brown",
  "Auburn",
  "Red",
  "Orange Red",
  "Copper",
  "Titian",
  "Strawberry Blond",
  "Light Blond",
  "Golden Blond",
  "Medium Blond",
  "Grey",
  "White",
];

const List<String> eyeColorData = [
  "Brown",
  "Amber",
  "Hazel",
  "Green",
  "Blue",
  "Gray",
];
